version: "2"
services:

  test-minio:
    image: minio/minio:latest
    ports:
      - "7000:9000"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    command: server /export
    restart: always


  test-webdav:
    image: test-rclone-webdav-server:latest
  #  volumes:
  #    - ./rclone/rclone.conf:/root/.config/rclone/rclone.conf
    environment:
      BUCKET: test-bucket
      AUTH_USER: admin
      AUTH_PASS: password
      BASE_URL: /
      RC_USER: admin
      RC_PASS: password
    depends_on:
      - test-minio
    links:
      - test-minio
    ports:
      - "80:80"
      - "5572:5572"
    restart: always
